backend/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('all_news/', views.all_news, name='all_news'),
    # path("article/<int:pk>/", views.detail, name="detail"),
    # path("post/create/", views.create_news, name="create_news"),
    # path("article/<slug:slug>/", views.detail, name="detail"),

    path('', views.AllNewsView.as_view(), name='all_news'),
    path('user/<str:username>', views.AllUserNewsView.as_view(), name='all_user_news'),
    path("article/create/", views.CreateNewsView.as_view(), name='create'),
    path('article/<int:pk>/', views.DetailNewsView.as_view(), name='detail'),
    path('article/<int:pk>/update/', views.UpdateNewsView.as_view(), name='update'),
    path('article/<int:pk>/delete/', views.DeleteNewsView.as_view(), name='delete'),

]

backend/project_roasitas/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

from rest_framework import routers, serializers, viewsets
from news.models import  News
from news.serializers import UserSerializer, NewsSerializer

# views
from news import views as news_views
from graphene_django.views import GraphQLView
from users import views as users_view 
from django.contrib.auth import views as auth_views
from mep import views as mep_views

router = routers.DefaultRouter()
router.register(r'user', news_views.UserViewSet)
router.register(r'news', news_views.NewsViewSet)
router.register(r'mep/status', mep_views.StatusViewSet)
router.register(r'mep/tasks', mep_views.TasksViewSet)






urlpatterns = [
    path('',include('news.urls', namespace="news")),
    path('admin/', admin.site.urls),
    path('register/', users_view.register, name='register'),
    path('profile/', users_view.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('polls/', include('polls.urls')),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('/tinymce/', include('tinymce.urls')),
    
    # GraphQL
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image


class News(models.Model):
    slug = models.SlugField(null=True)
    headline = models.CharField(max_length=250)
    news_content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, upload_to='news_image', )
    pub_date = models.DateField('Published Date', default=timezone.now)
    
    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 600 or img.width > 800:
            output_size = (600, 800)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse("news:detail", kwargs={"pk": self.pk})
    

class EmailSubscription(models.Model):
    subscriber = models.CharField(max_length=50)
    email = models.EmailField( max_length=254)

    def __str__(self):
        return self.email
        

backend/news/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, request
from .models import News
from django.template import loader
from django.views import generic
from django.contrib.auth.models import User, Group
from .models import News
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from rest_framework import viewsets
from .serializers import UserSerializer, NewsSerializer

def all_news(request):
    latest_news= News.objects.order_by('-pub_date')
    context = {'latest_news':latest_news}
    return render(request, 'news/all_news.html', context)

def detail(request, pk):
    detail = get_object_or_404(News,pk=pk)
    context = {'detail':detail}
    return render(request, 'news/news_detail.html', context)

def create_news(request):
    form_class = News
    form = form_class
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_vaild():
            form.save()
            messages.success(request, 'News Article Posted!')
            return redirect('all_news')

    return render(request, 'news/post/create.html', {'form':form})

class CreateNewsView(LoginRequiredMixin, generic.CreateView):
    model = News
    fields = ['slug','headline','news_content','image']

    def form_valid(self, form):
        form.instance.writer = self.request.user
        print(form.instance.writer)
        return super().form_valid(form)

class AllNewsView(generic.ListView):
    model = News
    template_name = 'news/all_news.html' # <app>/<model>_<viewtype>.html
    context_object_name ='latest_news'
    ordering = ['-pub_date']
    paginate_by = 5

   
class AllUserNewsView(generic.ListView):
    model = News
    template_name = 'news/all_user_news.html' # <app>/<model>_<viewtype>.html
    context_object_name ='latest_news'

    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username = self.kwargs.get('username'))
        return News.objects.filter(writer = user).order_by('-pub_date')

class UpdateNewsView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = News
    fields = ['slug','headline','news_content','image']
    context_object_name ="update"


    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.writer:
            return True
        return False

class DetailNewsView(generic.DetailView):
    model = News
    context_object_name ="detail"

class DeleteNewsView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = News
    success_url = ''

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.writer:
            return True
        return False



# # def article(request):
# #     latest_news = News.objects.order_by('-pub_date')[:5]
# #     template = loader.get_template('news/index.html')
# #     context = {'latest_news':latest_news}
# #     return render(request, 'news/index.html',context)


# ==========================================
# DRF ViewSet

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer


class NewsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    lookup_field = 'slug'
    queryset = News.objects.all()
    serializer_class = NewsSerializer

backend/templates/news/all_news.html
{% extends "base.html"%}
{% block content %}
    <h2> All News Listings 全部新聞 </h2>

    {% if latest_news %}
        <ul>
            {% for news in latest_news %} 
            <div class="card horizontal">
            <li>
            <img class= "article-img" src = "{{ news.writer.profile.image.url}}" />
                <div class="card-stacked">
                    <div class="card-content">
                        <p>{{ news.headline}} </p>
                        <p>{{ news.slug}} </p>
                        <a href="{% url 'news:all_user_news' news.writer.username %}"> Written By:{{ news.writer}}</a>
                    </div>
                    <div class="card-content">
                        <a href="{% url 'news:detail' news.id%}"> Read More 閱讀全篇</a>
                    </div>
                </div>
            </li>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p> No News Yet.</p>
    {% endif %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class = "btn" href="?page=1"> First 首頁</a>
            <a class = "btn" href="?page={{ page_obj.previous_page_number}}"> Previous 前頁 </a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num%}
                <a class = "btn " href="?page={{num}}"> {{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn" href="?page={{num}}"> {{num}}</a>

            {% endif %}
        {% endfor %}
            {% if page_obj.has_next %}
                <a class = "btn" href="?page={{ page_obj.next_page_number}}"> Next 下頁</a>
                <a class = "btn" href="?page={{ page_obj.paginator.num_pages}}"> Last 最後頁 </a>
         {% endif %}
    {% endif %}
{% endblock content%}

backend/templates/news/all_user_news.html
{% extends "base.html"%}
{% block content %}
    <h4 class="user_news_title"> {{view.kwargs.username }}'s {{ page_obj.paginator.count}} articles.</h4>
    {% if latest_news %}
        <ul>
            {% for news in latest_news %} 
            <div class="card horizontal">
            <li>
            <img class= "circle" src = "{{ news.writer.profile.image.url}}" />
                <div class="card-stacked">
                    <div class="card-content">
                        <p>{{ news.headline}} </p>
                        <p>{{ news.slug}} </p>
                        <a href="{% url 'news:all_user_news' news.writer.username %}"> Written By:{{ news.writer}}</a>
                    </div>
                    <div class="card-content">
                        <a href="{% url 'news:detail' news.id%}"> Read More 閱讀全篇</a>
                    </div>
                </div>
            </li>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p> No News Yet.</p>
    {% endif %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class = "btn blue-grey" href="?page=1"> First 首頁</a>
            <a class = "btn blue-grey-3" href="?page={{ page_obj.previous_page_number}}"> Previous 前頁 </a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num%}
                <a class = "btn blue-grey " href="?page={{num}}"> {{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn blue-grey" href="?page={{num}}"> {{num}}</a>

            {% endif %}
        {% endfor %}
            {% if page_obj.has_next %}
                <a class = "btn" href="?page={{ page_obj.next_page_number}}"> Next 下頁</a>
                <a class = "btn" href="?page={{ page_obj.paginator.num_pages}}"> Last 最後頁 </a>
         {% endif %}
    {% endif %}
{% endblock content%}

backend/templates/news/news_confirm_delete.html
{% extends "base.html"%}

{% block content%}
    <div class = "container">
        <h3> Upload News Article<br/> 上載新聞</h3>
        <form method ="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
            <legend class = "input-field col s6"> Delete Post</legend>
                <h3> Are you sure you want to delete the post "{{ news.title }}?"</h3>
                <div class="form-group">
                    <button class="waves-effect waves-light btn red darken-4"  type="submit"> Yes, Delete</button>
                    <a class="btn yellow darken-4" href= "{% url 'news:detail' news.id%}">Cancel</a>
                </div>
            </fieldset>
         </form>
    </div>
{% endblock content %}

backend/templates/news/news_detail.html
{% extends "base.html"%}
    {% load static%}
    {% block content %}
        <div class="headline">
            <h1> {{ detail.headline }}</h1>
            <small>{{ detail.pub_date|date:"F d,Y"}}</small>
        </div>
        <p> {{ detail.news_content }} </p>
        <img src={{ detail.image.url }} alt="{{ detail.headline }}"/>
        <a href="{% url 'news:all_user_news' detail.writer.username %}">Written By:  {{ detail.writer}}</a>
        {% if detail.writer == user %}
            <div class="update_delete_article">
                 <a class="waves-effect waves-light btn " href="{% url 'news:update' detail.id%}">Edit Article</a>
                 <a class="waves-effect waves-light btn red darken-4" href="{% url 'news:delete' detail.id%}">Delete Article</a>
            </div>
        {% endif %}
    {% endblock content%}

backend/templates/news/news_form.html
{% extends "base.html"%}

{% block content%}
    <div class = "container">
        <h3> Upload News Article<br/> 上載新聞</h3>
        <form method ="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
            <legend class = "input-field col s6"> News Article</legend>
                {{ form.as_p }}
                <button class="waves-effect waves-light btn"  type="submit"> Post</button>
            </fieldset>
         </form>
    </div>
{% endblock content %}