backend/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('all_news/', views.all_news, name='all_news'),
    # path("article/<int:pk>/", views.detail, name="detail"),
    # path("post/create/", views.create_news, name="create_news"),
    # path("article/<slug:slug>/", views.detail, name="detail"),

    path('', views.AllNewsView.as_view(), name='all_news'),
    path('user/<str:username>', views.AllUserNewsView.as_view(), name='all_user_news'),
    path("article/create/", views.CreateNewsView.as_view(), name='create'),
    path('article/<int:pk>/', views.DetailNewsView.as_view(), name='detail'),
    path('article/<int:pk>/update/', views.UpdateNewsView.as_view(), name='update'),
    path('article/<int:pk>/delete/', views.DeleteNewsView.as_view(), name='delete'),

]

backend/project_roasitas/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

from rest_framework import routers, serializers, viewsets
from news.models import  News
from news.serializers import UserSerializer, NewsSerializer

# views
from news import views as news_views
from graphene_django.views import GraphQLView
from users import views as users_view 
from django.contrib.auth import views as auth_views
from mep import views as mep_views

router = routers.DefaultRouter()
router.register(r'user', news_views.UserViewSet)
router.register(r'news', news_views.NewsViewSet)
router.register(r'mep/status', mep_views.StatusViewSet)
router.register(r'mep/tasks', mep_views.TasksViewSet)






urlpatterns = [
    path('',include('news.urls', namespace="news")),
    path('admin/', admin.site.urls),
    path('register/', users_view.register, name='register'),
    path('profile/', users_view.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('polls/', include('polls.urls')),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('/tinymce/', include('tinymce.urls')),
    
    # GraphQL
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/templates/base.html
{% load static %}
    {% include 'header.html' %}
    {% include 'nav.html' %}

    <div class="container">
            {% if messages %}
            {% for message in messages%}
                    <p> {{ message}}</p>
            {% endfor %}
                    
            {% endif %}
            {% block content%} {% endblock %}
    </div>
    {% include 'footer.html' %}

backend/templates/footer.html
{% load static %}

 <footer class="page-footer  green darken-4" style="margin-top: 1em">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Roasita's Editor</h5>
                <p class="grey-text text-lighten-4">A Quest For Delicious Chicken.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a href="{%  url 'news:all_news'%}">All News</a></li>
                  <li><a href="{%  url 'news:create'%}"> Write Story</a></li>
                  <a href="https://www.instagram.com/roasitas/" target="_blank"> Roasita's</a>

                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © {% now 'Y' %} Copyright Text
            </div>
          </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
        <script type='text/javascript' src={% static "js/materialize.min.js"%}></script>
        <script src="{% static 'js/news_index.js'%}"> </script>
    </body>
</html>

backend/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/materialize.min.css'%}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <meta name="theme-color" content="#fafafa">

        <title>Roasita's Editor</title>
</head>
<body>

backend/templates/nav.html
{% load static %}

        <nav class=" green darken-4">
        <div class="nav-wrapper">
        <a href="/" class="brand-logo" style="margin-left:1em">Roasita's Editor</a>

        <a href="#" data-target="mobile-demo" class="sidenav-trigger" onclick="sideNav"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down" style="padding-right:1em">
                <li><a href="{%  url 'news:all_news'%}">All News</a></li>
                <li><a href="{%  url 'news:create'%}"> Write Story</a></li>
                {% if user.is_authenticated %}
                        <li><a href="{%  url 'profile' %}">Profile</a></li>
                        <li><a href="{%  url 'logout' %}">Logout</a></li>
                {% else %}
                        <li><a href="{%  url 'login' %}">Login</a></li>
                        <li><a href="{%  url 'register' %}">Register</a></li>
                {% endif %}
        <li><small > Hi! {{ user.username}} </small></li>
        </ul>
        </div>
        </nav>


        <ul class="sidenav" id="mobile-demo">
            <li > <p style = 'margin-left:2em'>Hi! {{ user.username}}</p></li>
            <li><a href="{%  url 'news:all_news'%}">All News</a></li>
            <li><a href="{%  url 'news:create'%}"> Write Story</a></li>
            {% if user.is_authenticated %}
                <li><a href="{%  url 'profile' %}">Profile</a></li>
                <li><a href="{%  url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{%  url 'login' %}">Login</a></li>
                <li><a href="{%  url 'register' %}">Register</a></li>
            {% endif %}
        </ul>
  